name: Auto Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [ linux ]
        rustarch: [ x86_64, aarch64 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Get nightly toolchain
      run : rustup toolchain add nightly-${{ matrix.rustarch }}-unknown-linux-gnu
    - name: Add nightly rust-src
      run : rustup component add rust-src --toolchain nightly-${{ matrix.rustarch }}-unknown-linux-gnu
    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none" cargo +nightly build -Z build-std=std,panic_abort --target ${{ matrix.rustarch }}-unknown-linux-gnu --release
    - name: Run tests
      run: cargo test --verbose

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: seal-tool-${{ matrix.goos }}-${{ matrix.rustarch }}
        path: ./target/${{ matrix.rustarch }}-unknown-linux-gnu/release/seal-updater

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        goos: [ darwin ]
        rustarch: [ x86_64, aarch64 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Get nightly toolchain
      run: rustup toolchain add nightly-${{ matrix.rustarch }}-apple-darwin
    - name: Add nightly rust-src
      run : rustup component add rust-src --toolchain nightly-${{ matrix.rustarch }}-apple-darwin
    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none" cargo +nightly build -Z build-std=std,panic_abort --target ${{ matrix.rustarch }}-apple-darwin --release
    - name: Run tests
      run: cargo test --verbose

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: seal-tool-${{ matrix.goos }}-${{ matrix.rustarch }}
        path: ./target/${{ matrix.rustarch }}-apple-darwin/release/seal-updater

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        goos: [ windows ]
        rustarch: [ x86_64, i686 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Get target
      run: rustup target add ${{ matrix.rustarch }}-pc-windows-msvc
    - name: Build
      run: cargo build --target ${{ matrix.rustarch }}-pc-windows-msvc --verbose --release
    - name: Run tests
      run: cargo test --verbose

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: seal-tool-${{ matrix.goos }}-${{ matrix.rustarch }}
        path: ./target/${{ matrix.rustarch }}-pc-windows-msvc/release/seal-updater.exe
