name: Auto Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm64 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Get Rustup Nightly
      run : rustup toolchain add nightly-x86_64-unknown-linux-gnu
    - name: Add Nightly
      run : rustup component add rust-src --toolchain nightly
    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none" cargo +nightly build -Z build-std=std,panic_abort --target x86_64-unknown-linux-gnu --release
    - name: Run tests
      run: cargo test --verbose

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: seal-tool-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./target/x86_64-unknown-linux-gnu/release/seal-updater

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        goos: [ darwin ]
        goarch: [ amd64, arm64 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Get Rustup Nightly
      run: rustup toolchain add nightly-x86_64-apple-darwin
    - name: Add Nightly
      run : rustup component add rust-src --toolchain nightly
    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none" cargo +nightly build -Z build-std=std,panic_abort --target x86_64-apple-darwin --release
    - name: Run tests
      run: cargo test --verbose

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: seal-tool-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./target/x86_64-apple-darwin/release/seal-updater

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        goos: [ windows ]
        goarch: [ amd64 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Get Rustup Nightly
      run: rustup toolchain add nightly-x86_64-pc-windows-gnu
    - name: Add Nightly
      run : rustup component add rust-src --toolchain nightly
    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none" cargo +nightly build -Z build-std=std,panic_abort --target x86_64-pc-windows-gnu --release
    - name: Run tests
      run: cargo test --verbose

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: seal-tool-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./target/x86_64-pc-windows-gnu/release/seal-updater.exe
